var boxTemplate1 = '<section class="box active"> <h3>Box 1</h3> <div class="content"> <div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div></div></section>';
var boxTemplate2 = '<section class="box"> <h3>Box 1</h3> <div class="content"> <div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div></div></section>';
var boxTemplate3 = '<section class="box"> <h3>Box 1</h3> <div class="content"> <div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div></div></section>';
function newBox(title, isActive = false){
    var boxClass = isActive === true ? "box active" : "box";
    var boxTemplate = `<section class="${boxClass}"> <h3> ${title} </h3> <div class="content"> <div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div></div></section>`;
    return boxTemplate;
}
function boxesLoader(){
    return newBox("Box 1") + newBox("Box 2", true);
}
$(document).ready(function(){
    $("#section-boxes").html(boxesLoader());
  });
