var boxTemplate1 = '<section class="box active"> <h3>Box 1</h3> <div class="content"> <div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div></div></section>';
var boxTemplate2 = '<section class="box"> <h3>Box 1</h3> <div class="content"> <div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div></div></section>';
var boxTemplate3 = '<section class="box"> <h3>Box 1</h3> <div class="content"> <div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div><div class="row"> <div class="cell"> <img src="./img/thumbnail/default.png" alt="pokemon"></div> <div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div><div class="cell"></div></div></div></section>';
function boxesLoader(){
    return boxTemplate1 + boxTemplate2 + boxTemplate3;
}
$(document).ready(function(){
    $("#section-boxes").html(boxesLoader());
  });
